# see https://hub.docker.com/_/gcc/
image: gcc:6.1

test:
  stage: test
  before_script: 
    - apt update && apt -y install make cmake
    - git submodule update --init --recursive
  script:
    - ./ci.sh build
    - ./ci.sh run_tests
  cache:
    paths:
        - "build/"
