image: mrokkk/devel

test:
  stage: test
  script:
    - git submodule update --init --recursive
    - ./ci/run_tests.sh
  cache:
    paths:
        - "build/"

test-valgrind:
  stage: test
  script:
    - git submodule update --init --recursive
    - JOB=valgrind ./ci/run_tests.sh
  cache:
    paths:
        - "build/"

test-coverage:
  stage: test
  script:
    - git submodule update --init --recursive
    - JOB=coverage ./ci/run_tests.sh
  cache:
    paths:
        - "build/"

