# see https://hub.docker.com/_/gcc/
image: gcc:6.1

test:
  stage: test
  before_script:
    - apt update && apt -y install make cmake
    - git submodule update --init --recursive
  script:
    - ./ci/ci.sh ut
  cache:
    paths:
        - "build/"

test-valgrind:
  stage: test
  before_script:
    - apt update && apt -y install make cmake valgrind
    - git submodule update --init --recursive
  script:
    - VALGRIND=1 ./ci/ci.sh ut
  cache:
    paths:
        - "build/"

test-coverage:
  stage: test
  before_script:
    - apt update && apt -y install make cmake gcovr
    - git submodule update --init --recursive
  script:
    - COVERAGE=1 ./ci/ci.sh ut
  cache:
    paths:
        - "build/"
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
        - build/*.coverage.*

