image: mrokkk/devel

test:
  stage: test
  script:
    - ./ci/ci.sh ut
  cache:
    paths:
        - "build/"

test-valgrind:
  stage: test
  script:
    - VALGRIND=1 ./ci/ci.sh ut
  cache:
    paths:
        - "build/"

test-coverage:
  stage: test
  script:
    - COVERAGE=1 ./ci/ci.sh ut
  cache:
    paths:
        - "build/"

