# see https://hub.docker.com/_/gcc/
image: gcc:6.1

build:
  stage: build
  before_script: 
    - apt update && apt -y install make cmake
    - git submodule --init --recursive
  script: 
    - ./ci.sh build
  cache:
    paths:
        - "build/"

test:
  stage: test
  script:
    - ./ci.sh run_tests
