sudo: required

before_install:
  - docker pull mrokkk/devel

matrix:
    include:
        - env:
            - IMAGE=mrokkk/devel
            - COMPILER=g++
            - JOB=coverage
            - CODECOV=1
          services:
            - docker
        - env:
            - IMAGE=mrokkk/devel
            - COMPILER=clang++
            - JOB=coverage
          services:
            - docker
        - env:
            - IMAGE=mrokkk/devel
            - COMPILER=g++
            - JOB=valgrind
          services:
            - docker

language: cpp

script: ./ci.sh

after_success:
    - "if [ \"$CODECOV\" ]; then bash <(curl -s https://codecov.io/bash); fi"

