sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - valgrind

cache:
    - ccache
    - packages

language: cpp
script: ./ci.sh ut
---
language: cpp
script: VALGRIND=1 ./ci.sh ut
