sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6

cache:
    - ccache
    - packages

language: cpp
compiler: g++-6
script: ./ci.sh

