sudo: required
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - valgrind
            
compiler: g++-6

cache:
    - ccache
    - packages

language: cpp
script: CXX=g++-6 CC=gcc-6 ./ci.sh ut
---
language: cpp
script: CXX=g++-6 CC=gcc-6 VALGRIND=1 ./ci.sh ut
